apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config          # Name of the ConfigMap
  namespace: final        # Optional: Specify the namespace if not using "default"
data:
  DBHOST: "db-svc"   # 
  DBPORT: "3306"
  DATABASE: "employees"
  APP_NAMES: "Aldo Alvarado, Rony De Leon, Minh Trung Nguyen"
  APP_IMG: "uri"
  APP_PORT: "81"
  